services:
  - type: web
    name: chiknow-app
    env: python
    runtime: python-3.13.4
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python scripts/database/init_db.py
    startCommand: |
      python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DB_ENVIRONMENT
        value: produccion
      - key: DATABASE_URL
        fromDatabase:
          name: chiknow-db
          property: connectionString

databases:
  - name: chiknow-db
    plan: free
    databaseName: chiknow_db
    user: chiknow_user