services:
  - type: web
    name: chiknow-app
    env: python
    runtime: python-3.13.4
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    autoDeploy: true
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DB_ENVIRONMENT
        value: produccion
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: chiknow-db
          property: connectionString